# Use the official centos image as parent image
FROM akalinow/tensorflow-gpu:latest

# Define who is responsible for this Dockerfile
LABEL maintainer="Artur.Kalinowski@fuw.edu.pl"


USER root
RUN apt-get update
RUN apt -y install \
	cmake \
	libboost-all-dev
#	cargo


RUN pip3 install --upgrade iminuit
RUN pip3 install --upgrade nbdime
